private: true
packages:
  - 'packages/*'
dependencies:
  react: "^18.3.1"
  react-dom: "^18.3.1"
devDependencies:
  "@types/react": "^18.3.3"
  "@types/react-dom": "^18.3.0"
  typescript: "^5.5.4"
  ts-loader: "^9.5.1"
  webpack: "^5.94.0"
  webpack-dev-server": "^4.15.2"
  webpack-cli: "^5.1.4"
  html-webpack-plugin: "^5.6.0"
  css-loader: "^7.1.2"
  style-loader: "^4.0.0"
  less-loader: "^12.2.0"