private: true
packages:
  - 'packages/*'
dependencies:
  react: "^18.3.1"
  react-dom: "^18.3.1"
  "@antv/x6": "^2.18.1"
  "@antv/x6-plugin-clipboard": "^2.1.6"
  "@antv/x6-plugin-history": "^2.2.4"
  "@antv/x6-plugin-keyboard": "^2.2.3"
  "@antv/x6-plugin-selection": "^2.2.2"
  "@antv/x6-plugin-snapline": "^2.1.7"
  "@antv/x6-plugin-stencil": "^2.1.5"
  "@antv/x6-plugin-transform": "^2.1.8"
  "@antv/x6-plugin-scroller": "^2.0.10"
  "@antv/x6-react-shape": "^2.2.3"
devDependencies:
  "@types/react": "^18.3.3"
  "@types/react-dom": "^18.3.0"
  typescript: "^5.5.4"
  ts-loader: "^9.5.1"
  webpack: "^5.94.0"
  webpack-dev-server": "^4.15.2"
  webpack-cli: "^5.1.4"
  html-webpack-plugin: "^5.6.0"
  css-loader: "^7.1.2"
  style-loader: "^4.0.0"
  less-loader: "^12.2.0"